name: Android Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - run: git submodule update --init --recursive

      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - run: chmod +x gradlew

      - run: ./gradlew assembleCanary --no-daemon

      - run: find . -name "*.apk"

      - uses: actions/upload-artifact@v4
        with:
          name: Auxio_Canary
          path: "**/*.apk"
